name: Publish

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: digitalronin/ug
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: bundle exec middleman build --build-dir docs

  publish:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Release Github Pages
      uses: igolopolosov/github-action-release-github-pages@master
      env:
        GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_ACCESS_TOKEN }}
        GITHUB_PAGES_REPO_AUTHOR: digitalronin
        GITHUB_PAGES_REPO_NAME: cpug-publish
        GITHUB_PAGES_RELEASE_BRANCH: gh-pages
        PROJECT_BUILD_FOLDER: docs
