name: Publish

on:
  push:
    branches:
      - "main"

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install middleman
      run: gem install middleman

    - name: Build
      run: middleman build --build-dir docs

    - name: Release Github Pages
      uses: igolopolosov/github-action-release-github-pages@master
      env:
        GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_ACCESS_TOKEN }}
        GITHUB_PAGES_REPO_AUTHOR: digitalronin
        GITHUB_PAGES_REPO_NAME: cpug-publish
        GITHUB_PAGES_RELEASE_BRANCH: gh-pages
        PROJECT_BUILD_FOLDER: docs
