name: Publish

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: digitalronin/ug
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: bundle exec middleman build --build-dir docs
    - name: Run the script
      run: bin/publish.sh
      env:
        PUBLISHING_GIT_TOKEN: ${{ secrets.PUBLISHING_GIT_TOKEN }}
        GITHUB_PAGES_REPO_AUTHOR: digitalronin
        GITHUB_PAGES_REPO_NAME: cpug-publish
        GITHUB_PAGES_RELEASE_BRANCH: gh-pages
        PROJECT_BUILD_FOLDER: docs
